configfile: "config.json"
include: "precalling.conf"

ind = config['data']
outd = config['output']
genome = config["reference"]["genome"]
dbsnp = config["reference"]["db157"]
G1k = config["reference"]["g1k"]
m1kg = config["reference"]["m1kg"]
v6 = config["reference"]["V6"]
IDTv1 = config["reference"]["IDTv1"]

bwa = config["software"]["bwa"]
samtools = config["software"]["samtools"]
gatk = config["software"]["gatk"]

# 样本识别逻辑：涵盖了从原始数据到中间产物的所有可能状态
SAMPLES_bam, = glob_wildcards(outd + "/bam/{sample}.sorted.markdup.bam")
SAMPLES_fastp, = glob_wildcards(outd + "/" + config['fq_trim_dir'] + "/{sample}" + config["fq1_trim_suffix"])
SAMPLES_raw, = glob_wildcards(ind + "/{sample}" + config["fq1_suffix"])
SAMPLES = set(SAMPLES_bam + SAMPLES_fastp + SAMPLES_raw)

rule gatk_single_done:
    input:
        expand(outd + "/vcf/{sample}" + config["single_gvcf_suffix"], sample=SAMPLES)
    output:
        touch(outd + "/gatk.single.done")

rule gatk_BaseRecalibrator:
    input:
        bam = rules.gatk_markdup.output.bam,
        bai = rules.gatk_markdup.output.bai
    output:
        outd + "/bam/recal_{sample}WES.table"
    log:
        outd + "/logs/gatk_baserecalibrator/{sample}.log"
    benchmark:
        outd + "/benchmarks/{sample}.gatk_baserecalibrator.txt"
    threads:
        config["params"]["gatk"]["baserecalibrator_threads"]
    resources:
        mem_gb = config["params"]["gatk"]["baserecalibrator_mem_gb"]
    shell:
        """
        ({gatk} --java-options '-Xmx20G -XX:+UseParallelGC -XX:ParallelGCThreads={threads}' \
            BaseRecalibrator \
            -R {genome} \
            -I {input.bam} \
            -O {output} \
            --known-sites {dbsnp} \
            --known-sites {G1k} \
            --known-sites {m1kg}) 2> {log}
        """

rule gatk_ApplyBQSR:
    input:
        bam = rules.gatk_markdup.output.bam,
        table = rules.gatk_BaseRecalibrator.output
    output:
        outd + "/bam/{sample}.sorted.markdup.BQSR.bam"
    log:
        outd + "/logs/gatk_applyBQSR/{sample}.log"
    benchmark:
        outd + "/benchmarks/{sample}.gatk_applyBQSR.txt"
    threads:
        config["params"]["gatk"]["applybqsr_threads"]
    resources:
        mem_gb = config["params"]["gatk"]["applybqsr_mem_gb"]
    shell:
        """
        ({gatk} --java-options '-Xmx20G -XX:+UseParallelGC -XX:ParallelGCThreads={threads}' \
            ApplyBQSR \
            --bqsr-recal-file {input.table} \
            -R {genome} \
            -I {input.bam} \
            -O {output}) 2>{log}
        
        # 按用户要求，手动清理中间文件
        rm -rf {outd}/bam/{wildcards.sample}.sorted.markdup.bam
        """

rule gatk_hc:
    input:
        bam = rules.gatk_ApplyBQSR.output
    output:
        outd + "/gvcf/{sample}" + config["single_gvcf_suffix"]
    threads:
        config["params"]["gatk"]["hc_threads"]
    resources:
        mem_gb = config["params"]["gatk"]["hc_mem_gb"]
    log:
        outd + "/logs/gatk_hc/{sample}.log"
    benchmark:
        outd + "/benchmarks/{sample}.gatk_hc.txt"
    shell:
        """
        ({gatk} --java-options '-Xmx24G -XX:+UseParallelGC -XX:ParallelGCThreads={threads}' \
            HaplotypeCaller \
            -I {input.bam} \
            -O {output} \
            -R {genome} \
            -D {dbsnp} \
            -L {IDTv1} \
            --interval-padding 100 \
            -ERC GVCF \
            -G StandardAnnotation \
            -G StandardHCAnnotation \
            --native-pair-hmm-threads {threads} \
            -stand-call-conf 10) 2>{log}
        """
