configfile: "config.json"
include: "gatk_single.conf"

ind=config['data']
outd=config['output']

genome=config["reference"]["genome"]
dbsnp=config["reference"]["db157"]
G1k=config["reference"]["g1k"]
m1kg=config["reference"]["m1kg"]
v6=config["reference"]["V6"]

bwa=config["software"]["bwa"]
samtools=config["software"]["samtools"]
gatk=config["software"]["gatk"]

SAMPLES_gvcf, =glob_wildcards(outd+"/vcf/{sample}"+config['single_gvcf_suffix'])
SAMPLES_bam, =glob_wildcards(outd+"/bam/{sample}.sorted.markdup.bam")
SAMPLES_fastp, =glob_wildcards(outd+"/"+config['fq_trim_dir']+"/{sample}"+config["fq1_trim_suffix"])
SAMPLES_raw, =glob_wildcards(ind+"/{sample}"+config["fq1_suffix"])
SAMPLES=set(SAMPLES_gvcf+SAMPLES_bam+SAMPLES_fastp+SAMPLES_raw)

rule gatk_done:
	input:
		outd+"/"+config["combine_vcf"]
rule make_gvcf_list:
	input:
		list=expand(outd+"/vcf/{sample}"+config['single_gvcf_suffix'], sample=SAMPLES)
	output:
		temp(outd+"/gvcf.list")
	run:
		with open(output[0], 'w') as ot:
			for vcf in input.list:
				ot.writelines(vcf+"\n")
rule gatk_CombineGVCFs:
	input:
		list=rules.make_gvcf_list.output,
	output:
		outd+"/"+config["combine_g_vcf"]
	threads:
		config['params']['gatk']['combinegvcf_threads']
    resources:
        mem_gb = config["params"]["gatk"]["combinegvcf_mem_gb"]
	log:
		outd+"/logs/gatk_combine/logs"
	benchmark:
		outd+"/benchmarks/gatk_combine.txt"
	shell:
		"""
		({gatk} CombineGVCFs --java-options '-Xmx250G -XX:+UseParallelGC \
            -XX:ParallelGCThreads={threads}' -V {input.list} -R {genome} -O {output} \
		    -G StandardAnnotation -G StandardHCAnnotation -D {dbsnp} \
		    -L {v6}) 2>{log}
		"""
rule gatk_GenotypeGVCFs:
	input:
		vcf=rules.gatk_CombineGVCFs.output,
	output:
		outd+"/"+config["combine_vcf"]
	threads:
		config['params']['gatk']['genotypegvcf_threads']
    resources:
        mem_gb = config["params"]["gatk"]["genotypegvcf_mem_gb"]
	log:
		outd+"/logs/gatk_genotype/logs"
	benchmark:
		outd+"/benchmarks/gatk_genotype.txt"
	shell:
		"""
		({gatk} GenotypeGVCFs --java-options '-Xmx250G -XX:+UseParallelGC \
            -XX:ParallelGCThreads={threads}' -V {input.vcf} -R {genome} -O {output} \
		    -D {dbsnp} \
		    -G StandardAnnotation -G StandardHCAnnotation \
		    -L {v6}) 2>{log}
		"""
