configfile: "config.json"
include: "trimfastq.conf"

genome = config["reference"]["genome"]
ind = config['data']
outd = config['output']

bwa = config["software"]["bwa"]
samtools = config["software"]["samtools"]
gatk = config["software"]["gatk"]

# 样本识别逻辑：取原始文件和已过滤文件的并集
SAMPLES_fastp, = glob_wildcards(outd + "/" + config['fq_trim_dir'] + "/{sample}" + config["fq1_trim_suffix"])
SAMPLES_raw, = glob_wildcards(ind + "/{sample}" + config["fq1_suffix"])
SAMPLES = set(SAMPLES_raw + SAMPLES_fastp)
#SAMPLES=SAMPLES_raw

rule precalling_done:
    input:
        expand(outd + "/bam/{sample}.sorted.markdup.bam", sample=SAMPLES)
    output:
        touch(outd + "/preprocessing.done")

rule bwa_map_sort:
    input:
        R1 = outd + "/" + config['fq_trim_dir'] + "/{sample}" + config["fq1_trim_suffix"],
        R2 = outd + "/" + config['fq_trim_dir'] + "/{sample}" + config["fq2_trim_suffix"]
    output:
        bam = temp(outd + "/bam/{sample}.sorted.bam")
    threads:
        # 申请的总线程 = BWA线程 + Samtools线程
        config["params"]['bwa']["threads"] + config["params"]['samtools']["threads"]
    resources:
        # 申请的总内存 = BWA内存 + Samtools内存
        mem_gb = config["params"]['bwa']["mem_gb"] + config["params"]["samtools"]["mem_gb"]
    params:
        rg = r"@RG\tID:{sample}WES\tSM:{sample}\tLB:" + config['params']['bwa']['LB'] + r"\tPL:" + config['params']['bwa']['PL'],
        bwa_threads = config["params"]['bwa']["threads"],
        sort_threads = config["params"]['samtools']["threads"],
        # 每个排序线程分配的内存 (如 "4G")
        sort_mem = str(config["params"]["samtools"]["mem_gb"] // config["params"]['samtools']["threads"]) + "G"
    log:
        outd + "/logs/bwa_mem/{sample}.log"
    shell:
        """
        # 使用 params 中定义的变量，避免 shell 解析 config 字典报错
        ({bwa} mem -t {params.bwa_threads} -R '{params.rg}' {genome} {input.R1} {input.R2} | \
        {samtools} sort -@ {params.sort_threads} -m {params.sort_mem} -o {output.bam} -T {output.bam}.tmp -) 2>{log}
        """

rule gatk_markdup:
    input:
        rules.bwa_map_sort.output.bam
    output:
        bam = outd + "/bam/{sample}.sorted.markdup.bam",
        bai = outd + "/bam/{sample}.sorted.markdup.bai",
        txt = outd + "/bam/{sample}.markdup_metrics.txt"
    threads:
        config["params"]["gatk"]["markdup_threads"]
    resources:
        mem_gb = config["params"]["gatk"]["markdup_mem_gb"]
    params:
        rmdup = config["params"]["gatk"]["rmdup"],
    log:
        outd + "/logs/gatk_markdup/{sample}.log"
    benchmark:
        outd + "/benchmarks/{sample}.gatk_markdup.txt"
    shell:
        """
        ({gatk} --java-options '-Xmx24G -XX:+UseParallelGC -XX:ParallelGCThreads={threads}' MarkDuplicates \
            -I {input} \
            -O {output.bam} \
            -M {output.txt} \
            --CREATE_INDEX true \
            --VALIDATION_STRINGENCY SILENT \
            --REMOVE_SEQUENCING_DUPLICATES {params.rmdup}) 2>{log}
        """
